### ISSUE TITLE
Fathom Lable field is automatically refreshed / cleared

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/fathom-fox#28]
**[Affected versions]:**
- Firefox Nightly 67.0a1 
- FathomFox 2.3.1

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Latest FathomFox add-on is installed
- Link with issues: 
  - https://www.glassesusa.com/

**[Steps to reproduce]:**
1. Open the above link into Firefox.
2. Click on "My Account" button.
3. Right-click on the Username field and Inspect Element.
4. Inspected element is selected.
5. Reach the Fathom tab from DevTools.
6. Type something into "Label" field.
6. Observe the "Label" field.

**[Expected results]:**
- The characters written are displayed.

**[Actual results]:**
-  "Label" field is cleared when Tab Title is automatically changed

**[Notes]:**
- Screen recorder of the issue attached:

![label_field_refreshed](https://user-images.githubusercontent.com/9248513/53820266-143fea00-3f74-11e9-86c6-dca98be3d3ef.gif)

**Comment by erikrose** [comment]
I think 206fb4cd90c4fe3bd53a4f95b8681ed69ea585b0, when I release it, will solve this issue. RIght now, the field is being cleared (and, in fact, the entire panel is being redrawn) because the tab has been updated and it think you've navigated to a new page.

I'm in the midst of the cascade of releases I need to do to get a neural-net-based optimizer out in the world. FathomFox is part of that. You should see a fix in the next week.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on Nightly Build ID: 20190331215222 with FathomFox 3.0 and it is no longer reproducible. Thus, marking this as Verified - Fixed.
