### ISSUE TITLE
Upgrade to latest freeze-dry library

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#34]
It may improve iframe serialization, which is supposed to work but, in my experience, does not happen at all.

**Comment by erikrose** [comment]
Note an error when trying to do this: https://github.com/mozilla/fathom-fox/issues/38#issuecomment-509323737

**Comment by danielhertenstein** [comment]
It seems the circular dependencies that are warned when running `yarn build`
![circular](https://user-images.githubusercontent.com/5586735/61324396-51e53700-a7e0-11e9-800b-f3528e8713cc.png)
are important and could very well be the reason fathom-fox does not work when upgrading freeze-dry to 0.2.4.

freeze-dry 0.2.4 (well starting with 0.2.1) depends on postcss. I have come across this issue in the postcss repository that makes me believe postcss is the problem: https://github.com/postcss/postcss/issues/1030.

Because this is the only lead I have, I'm going to follow it.

**Comment by danielhertenstein** [comment]
Closed by #45
