### ISSUE TITLE
Add a keystroke that triggers freeze

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#41]
When we were capturing login-form samples, some forms were in a menu that appeared only when we hovered over an element. This made it impossible to capture the page with the form showing. Add a key shortcut that triggers a freeze so we can grab such things.

**Comment by danielhertenstein** [comment]
Any preference on the key that we use? `Shift + F`?

**Comment by danielhertenstein** [comment]
@erikrose I have something that works!

One small problem though: because the labels in the dev panel aren't applied until the text box loses focus, you can have the situation where a person updates the label, hits the keypress to save the page, and then their page doesn't have the appropriate label.

We could change the event listener for the label text box to listen for input events and update every X milliseconds or once it's been awhile since the user has stopped typing.

**Comment by erikrose** [comment]
I'm not really concerned with using the keystroke to save the page while typing into the dev tools panel. (In fact, I wouldn't even list it in the UI near that Save button, due to the problem you cite—good find, btw.) The main use case is saving pages while keeping hover states active, in which cases we come back and label the hover-shown elements (and re-save) later, or we've already labeled them while they were invisible (but need to save the page with them shown so isVisible doesn't filter them out).

**Comment by danielhertenstein** [comment]
Works for me!
