### ISSUE TITLE
Evaluating behavior inconsistent for rulesets with dependent types

### ISSUE THREAD

**Issue by danielhertenstein** [mozilla/fathom-fox#50]
When testing the Evaluate page on the Price Tracker ruleset, @biancadanforth found that no BAD labels were applied to pages evaluated using the `title` type (see [here](https://github.com/mozilla/fathom-fox/pull/47)). I believe there are no labels applied because the ruleset does not find any candidate elements when evaluating the ruleset (see my last comment in the pull request referenced above).

Tied to this issue is [this issue](https://github.com/mozilla/fathom/issues/98) @erikrose worked on.

**Comment by erikrose** [comment]
Your belief is correct! The whole BAD-labeling thing is, perhaps obviously, a cheap move on my part to get badness showing to the user (me at the time) without having to write more UI. When it finds no spurious element, nothing happens, because…well…what would happen?

I recommend we think about this when we do the design for #39.
