### ISSUE TITLE
It's not obvious that the coeffs in the UI change over time

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#6]
Bianca thought she had to wait until the progress bar completed. Ideas:

* Move from a progress bar to a barber pole (which I don't think `<meter>` helps us with), and have the start button turn into a stop or pause button when clicked. (I've wanted a pause button several times during debugging—or when getting on a plane.)
* Literally say that the values update in realtime. (But users don't read.)
* Make the coeffs and other output stuff pulse or wiggle or throb or something.

Please come up with something better than these. :-)

**Comment by globau** [comment]
here's what i'm thinking we do:
- changed from `<meter>` to a generic spinner (e.g. https://codepen.io/anon/pen/xJQjEg)
- add `stop` and `pause` buttons
- label the coeffs, accuracy, and succ/fail output as "In Progress" or "Current State" or similar, perhaps with different styling to indicate it isn't "final" (eg. slightly dimmed)
- when the work stops, either due to completing the iterations or the user hitting `stop`, change the output to "Final Results" or similar.

side note: `<meter>` is the wrong element; it's designed for displaying a measurement on a known scale (eg. disk usage).  `<progress>` is what you'd generally use, and it supports an indeterminate value (ie. a barber pole spinner).

**Comment by erikrose** [comment]
> changed from <meter> to a generic spinner

I totally missed `<progress>`! Let's use that! It's semantic (hey, why not?), and it should look good in the current layout. Heck, it may even meld with the native platform better.

> add stop and pause buttons

I was going to say "Why stop?", but you're right: once we get multiple rulesets, stop actually makes sense, because there's something else to do than restart the current run.

>  the coeffs, accuracy, and succ/fail output as "In Progress" or "Current State" or similar, perhaps with different styling to indicate it isn't "final" (eg. slightly dimmed)

"Best so far:"? I vote to forgo the dimming for the sake of readability. (I dimmed some of the explanatory text and still wake up screaming. :-))

Good ideas! Thank you!

**Comment by erikrose** [comment]
FathomFox Trainer is deprecated in favor of fathom-train CLI tool, which has a nice bar graph and converges.
