### ISSUE TITLE
Solve corpus-collection freezes

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom-fox#8]
Some pages, like https://tutorials-raspberrypi.com/google-chrome-for-raspberry-pi/, generate the spinny pizza of death—but only during automated corpus capture, not when freezing using the dev panel.

**Comment by globau** [comment]
there's two places where stalling/timeouts happen: while waiting for all the content to load, and during the freeze process.

from what i've seen issues waiting for the page to load isn't that common, but tends to happen on very ad heavy pages.  we should set a timeout and see if we can cancel the loading (ie. perform the same action as clicking on the "stop" button).  that changes the tab's state to "complete" allowing the freeze process to start.

freeze itself is the greater issue.  i upgraded to 0.2.0 which doesn't appear to have resolved the issue; in fact it runs significantly slower on some pages (likely due to it performing more work).  my guess is it's stuck in an infinite loop trying to resolve resources.


i plan to start with setting timeouts on both of these; i'm thinking 30 seconds for page load, and 3 minutes for freezing (both values are a SWAG).  then i'll instrument 0.2.0 of freeze and see if i can determine what's causing the issue in order to fix it upstream.

**Comment by erikrose** [comment]
Sounds good. I bet you're going to end up with longer timeouts: I've had ad-heavy pages legitimately (insofar as such abuses can be legitimate) take 5 minutes to load. It's absurd.

One nice thing about freeze-dry 0.2.0: he added callbacks to customize just about everything. I'm not sure if there's a timeout callback, but I wouldn't be surprised, and he'd likely be very amenable to adding one.

**Comment by globau** [comment]
poking at this some more it's evident there's race conditions around creating a window/tab and waiting for it to complete.

i'm exploring switching to a state machine line processing pipeline: hook up the tab completion event handlers up front, and use custom messages to progress the state.

**Comment by globau** [comment]
poking at this some more it's evident there's race conditions around creating a window/tab and waiting for it to complete.

i'm exploring switching to a state machine line processing pipeline: hook up the tab completion event handlers up front, and use custom messages to progress the state.

**Comment by globau** [comment]
after tiding that up, including error handling, it looks like when freeze-dry stops it's throwing `can't access dead object`.  sounds like the dom is changing while freeze-dry is walking it, tripping it up.

**Comment by erikrose** [comment]
Interesting. And making a freeze-drier that works around that sounds like an interesting problem as well—in the worst sense of the word. I see the front of the pipeline [uses Node.cloneNode](https://github.com/WebMemex/freeze-dry/blob/58bf81007b4f90accefd4b71e0106da8b64a5b14/src/capture-dom.js#L31), at least in 0.2.0. So, if it's DOM-changing that's tripping it up, that implies cloneNode is not atomic, which sounds like an awfully bad thing. (I can't seem to easily find docs on whether it's supposed to be.) If it's non-atomic, then at least it must itself have figured out *something* to do when the DOM changes out from under it.
